---
- name: Get Flutter Version
  command: flutter --version
  register: flutter_version
  changed_when: False

- name: Check for Flutter SDK
  stat:
    path: "~/Downloads/flutter_macos_v{{ flutter_target_version }}-beta.zip" 
  register: flutter_sdk

- name: Download Flutter SDK
  get_url:
    url: "https://storage.googleapis.com/flutter_infra/releases/beta/macos/flutter_macos_v{{ flutter_target_version }}-beta.zip"
    dest: ~/Downloads
  when: flutter_sdk.stat.exists == False and flutter_version.stdout_lines[0].split()[1] != flutter_target_version 
  register: flutter_update 

- name: Extract Flutter
  unarchive:
    src: "~/Downloads/flutter_macos_v{{ flutter_target_version }}-beta.zip"
    dest: ~/Git
  when: flutter_latest_version

- name: Add Flutter to Path
  lineinfile:
    path: /etc/paths
    line: /Users/brad/Git/flutter/bin
  become: yes

- name: Update Flutter
  command: flutter upgrade

- name: Delete downloaded Flutter SDK
  file:
    path: "~/Downloads/flutter_macos_v{{ flutter_target_version }}-beta.zip"
    state: absent
...